import type { WooCommerceProduct } from '@/lib/woocommerce';

const scentedCandlesCategory = {
  id: 101,
  name: 'Scented Candles',
  slug: 'scented-candles',
};

const waxMeltsCategory = {
  id: 102,
  name: 'Wax Melts',
  slug: 'wax-melts',
};

const giftSetsCategory = {
  id: 103,
  name: 'Gift Sets',
  slug: 'gift-sets',
};

const customCandlesCategory = {
  id: 104,
  name: 'Custom Candles',
  slug: 'custom-candles',
};

export const SAMPLE_PRODUCTS: WooCommerceProduct[] = [
  {
    id: 9001,
    name: 'Lavender Calm Jar Candle',
    slug: 'lavender-calm-jar-candle',
    permalink: '/products/lavender-calm-jar-candle',
    type: 'simple',
    status: 'publish',
    featured: true,
    description:
      '<p>A soothing lavender candle crafted for evening wind-down rituals.</p><p>Burn time: 45+ hours.</p>',
    short_description: 'Calming lavender scent with a clean, even burn.',
    sku: 'CG-LAV-001',
    price: '24.00',
    regular_price: '24.00',
    sale_price: '',
    on_sale: false,
    purchasable: true,
    total_sales: 120,
    virtual: false,
    downloadable: false,
    images: [
      {
        id: 9101,
        src: 'https://images.pexels.com/photos/671956/pexels-photo-671956.jpeg?auto=compress&cs=tinysrgb&w=1200',
        name: 'Lavender Calm Jar Candle',
        alt: 'Lavender candle in glass jar',
      },
      {
        id: 9102,
        src: 'https://images.pexels.com/photos/278508/pexels-photo-278508.jpeg?auto=compress&cs=tinysrgb&w=1200',
        name: 'Lavender Calm Candle Detail',
        alt: 'Lit candle close-up',
      },
    ],
    categories: [scentedCandlesCategory],
    tags: [
      { id: 201, name: 'lavender', slug: 'lavender' },
      { id: 202, name: 'relaxing', slug: 'relaxing' },
    ],
    stock_status: 'instock',
    stock_quantity: 32,
    manage_stock: true,
  },
  {
    id: 9002,
    name: 'Vanilla Ember Soy Candle',
    slug: 'vanilla-ember-soy-candle',
    permalink: '/products/vanilla-ember-soy-candle',
    type: 'simple',
    status: 'publish',
    featured: false,
    description:
      '<p>Warm vanilla and amber notes designed for cozy evenings and gifting.</p><p>Burn time: 50+ hours.</p>',
    short_description: 'Rich vanilla and amber blend in a reusable vessel.',
    sku: 'CG-VAN-002',
    price: '21.00',
    regular_price: '26.00',
    sale_price: '21.00',
    on_sale: true,
    purchasable: true,
    total_sales: 84,
    virtual: false,
    downloadable: false,
    images: [
      {
        id: 9103,
        src: 'https://images.pexels.com/photos/278508/pexels-photo-278508.jpeg?auto=compress&cs=tinysrgb&w=1200',
        name: 'Vanilla Ember Soy Candle',
        alt: 'Warm candle glow',
      },
    ],
    categories: [scentedCandlesCategory],
    tags: [
      { id: 203, name: 'vanilla', slug: 'vanilla' },
      { id: 204, name: 'amber', slug: 'amber' },
    ],
    stock_status: 'instock',
    stock_quantity: 25,
    manage_stock: true,
  },
  {
    id: 9003,
    name: 'Citrus Sunrise Candle',
    slug: 'citrus-sunrise-candle',
    permalink: '/products/citrus-sunrise-candle',
    type: 'simple',
    status: 'publish',
    featured: false,
    description:
      '<p>A fresh citrus blend to brighten mornings and energize your space.</p><p>Burn time: 40+ hours.</p>',
    short_description: 'Bright citrus fragrance with clean soy wax.',
    sku: 'CG-CIT-003',
    price: '22.00',
    regular_price: '22.00',
    sale_price: '',
    on_sale: false,
    purchasable: true,
    total_sales: 58,
    virtual: false,
    downloadable: false,
    images: [
      {
        id: 9104,
        src: 'https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg?auto=compress&cs=tinysrgb&w=1200',
        name: 'Citrus Sunrise Candle',
        alt: 'Candle display shelf',
      },
    ],
    categories: [scentedCandlesCategory],
    tags: [
      { id: 205, name: 'citrus', slug: 'citrus' },
      { id: 206, name: 'fresh', slug: 'fresh' },
    ],
    stock_status: 'instock',
    stock_quantity: 40,
    manage_stock: true,
  },
  {
    id: 9004,
    name: 'Cozy Cabin Wax Melt Set',
    slug: 'cozy-cabin-wax-melt-set',
    permalink: '/products/cozy-cabin-wax-melt-set',
    type: 'simple',
    status: 'publish',
    featured: false,
    description:
      '<p>Six-pack wax melt sampler with wood, spice, and vanilla-inspired blends.</p><p>Includes reusable storage tin.</p>',
    short_description: 'Wax melt set with six cozy seasonal scents.',
    sku: 'CG-WAX-004',
    price: '18.00',
    regular_price: '18.00',
    sale_price: '',
    on_sale: false,
    purchasable: true,
    total_sales: 37,
    virtual: false,
    downloadable: false,
    images: [
      {
        id: 9105,
        src: 'https://images.pexels.com/photos/671956/pexels-photo-671956.jpeg?auto=compress&cs=tinysrgb&w=1200',
        name: 'Cozy Cabin Wax Melt Set',
        alt: 'Wax melt and candle arrangement',
      },
    ],
    categories: [waxMeltsCategory],
    tags: [
      { id: 207, name: 'wax-melts', slug: 'wax-melts' },
      { id: 208, name: 'cozy', slug: 'cozy' },
    ],
    stock_status: 'instock',
    stock_quantity: 18,
    manage_stock: true,
  },
  {
    id: 9005,
    name: 'Weekend Relax Gift Box',
    slug: 'weekend-relax-gift-box',
    permalink: '/products/weekend-relax-gift-box',
    type: 'simple',
    status: 'publish',
    featured: true,
    description:
      '<p>Gift-ready box featuring two candles and one wax melt bar for a complete relaxation set.</p>',
    short_description: 'Gift set with curated candle and wax melt favorites.',
    sku: 'CG-GFT-005',
    price: '48.00',
    regular_price: '54.00',
    sale_price: '48.00',
    on_sale: true,
    purchasable: true,
    total_sales: 26,
    virtual: false,
    downloadable: false,
    images: [
      {
        id: 9106,
        src: 'https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg?auto=compress&cs=tinysrgb&w=1200',
        name: 'Weekend Relax Gift Box',
        alt: 'Candle gift box presentation',
      },
    ],
    categories: [giftSetsCategory],
    tags: [
      { id: 209, name: 'gift', slug: 'gift' },
      { id: 210, name: 'bundle', slug: 'bundle' },
    ],
    stock_status: 'instock',
    stock_quantity: 12,
    manage_stock: true,
  },
  {
    id: 9900,
    name: 'Comfort Giggle Custom Candle',
    slug: 'comfort-giggle-custom-candle',
    permalink: '/products/comfort-giggle-custom-candle',
    type: 'simple',
    status: 'publish',
    featured: true,
    description:
      '<p>Create your own custom candle by choosing your scent profile, jar color, size, and label text.</p><p>According to your selected options, we will send you the price and production time.</p>',
    short_description: 'Choose your options and we will send the price.',
    sku: 'CG-CUSTOM-001',
    price: '32.00',
    regular_price: '32.00',
    sale_price: '',
    on_sale: false,
    purchasable: true,
    total_sales: 14,
    virtual: false,
    downloadable: false,
    images: [
      {
        id: 9107,
        src: 'https://images.pexels.com/photos/278508/pexels-photo-278508.jpeg?auto=compress&cs=tinysrgb&w=1200',
        name: 'Comfort Giggle Custom Candle',
        alt: 'Custom candle with personalized label',
      },
    ],
    categories: [customCandlesCategory],
    tags: [
      { id: 211, name: 'custom', slug: 'custom' },
      { id: 212, name: 'personalized', slug: 'personalized' },
    ],
    stock_status: 'instock',
    stock_quantity: 15,
    manage_stock: true,
  },
];
